language: node_js
node_js:
- stable
sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_78a9d0ec5f1e_key -iv $encrypted_78a9d0ec5f1e_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: .travis/deploy.sh
    on:
      branch: master