language: node_js
node_js:
- stable
sudo: false

# This keeps the "add <your-host.tld> to known_hosts" prompt from popping up
addons:
  ssh_known_hosts:
  - 149.210.172.104:22 # if your server uses a different port for ssh

before_install:
- openssl aes-256-cbc -K $encrypted_78a9d0ec5f1e_key -iv $encrypted_78a9d0ec5f1e_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: "NODE_ENV=production npm run build:production && .travis/deploy.sh"
    on:
      branch: master