language: node_js
node_js:
- stable
- '6'
- '4'
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_78a9d0ec5f1e_key -iv $encrypted_78a9d0ec5f1e_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
